[package]
name = "block_effects"
version = "0.1.0"
authors = ["mathijsd <mathijs.delabie@bricsys.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
proc-macro = true
